### PR TITLE
TREZOR Firmware 1.3.6 support

### PR DESCRIPTION
**Pull request by martin-lizner**

### CODE REVIEW

**Comment by bgok** [comment]
I will pull this into the devel branch later this weekend. Thanks!

**Comment by martin-lizner** [comment]
Thanks, further detail can be found in your Helpdesk ticket #1230

**Comment by prusnak** [comment]
I would rather see all communication public rather than communicating in some internal tracker behind the closed doors.

**Comment by dstanchfield** [comment]
We wrote a blog post about it here: https://multibit.org/blog/2016/06/27/trezor-version-1.3.6.html

**Comment by jhoenicke** [comment]
I looked over the patch and there is a problem.   The old code was correct for Trezor >=1.3.6 and incorrect for Trezor <= 1.3.5, while the new code is basically always incorrect.

So under the hid4java API, the report_id is the third parameter of the write, while the byte array should not include the report_id.  This is different from the native C API where the report_id is added in front of data.  If you look at the HidApi.write(), it adds the report_id back to the array, with one exception... Windows 8/10. Why? To make the old buggy code work with previous versions of Trezor under Windows!

For Trezor <= 1.3.5, the report_id should be 63, and the data should not include the 63.  So the old code was incorrect which lead to this bug keepkey/multibit-hd#379.  Unfortunately at the time the real cause (report_id being 0 instead of 63 and data including the report_id) was not correctly determined.  This lead to the "fix" in gary-rowe/hid4java#12, and the fix of the fix in  gary-rowe/hid4java#36.

I suggest reverting the special Windows 8/10 fix in hid4java and fixing the Trezor code.

For Trezor 1.3.6:  report_id = 0, buffer 64 bytes including first byte 63.
For Trezor 1.3.5 and lower: report_id = 63, buffer 63 bytes not including 63.

I can supply an improved pull request for this library, once the wrong fix in hid4java is reverted (paging @gary-rowe).  The dropReportIdZero should not be set under Windows 8/10. It was a bug in the TrezorV1HardwareWallet.

**Comment by jhoenicke** [comment]
Once hid4java is reverted to not ignore report_id 0, this patch should work:

https://github.com/keepkey/multibit-hardware/compare/develop...jhoenicke:develop

It's a minimal change on @martin-lizner's patch that splits out the report_id from the packet.  I also use writeDevice in the version detection.

**Comment by martin-lizner** [comment]
@jhoenicke thanks for the update! I will gladly merge it into this pull request. However changes to hid4java should be made first. I suggest you raise a new issue or PR in hid4java project.

Just for the record, this PR works fine for mentioned firmwares, we just need to implement it better without workarounding some older issues.

**Comment by slush0** [comment]
Any progress in this?

**Comment by bgok** [comment]
The change is integrated. There is one more bug fix we are working on for the release. If everything goes well, there will be a release this week or next.

**Comment by martin-lizner** [comment]
Which hid4java version are you testing on? There are problems with latest master dev (intended to be 0.5.0) not switching Trezor to ready state.

**Comment by gary-rowe** [comment]
I'm back from vacation now, so I'll be able to look at the hid4java support work required.

**Comment by bgok** [comment]
0.5.0 isn't tagged yet. I think @gary-rowe is still working on it. He is unavailable to work on it at the moment, but he told @kliyer that he will work on it soon. We will probably release with 0.4.0 and get 0.5.0 in the next release.

**Comment by bgok** [comment]
Thanks @gary-rowe.

**Comment by kliyer** [comment]
@jhoenicke do you mind if  we pull these changes into a SNAPSHOT so that we can get this fix released? https://github.com/keepkey/multibit-hardware/compare/develop...jhoenicke:develop

**Comment by jhoenicke** [comment]
Feel free to use my patch as you like.  It may depend on my pull request to hid4java (gary-rowe/hid4java#43), to work under Windows.  It would be good to test it with Trezor firmware 1.3.5 and 1.3.6 and also with keepkey under various Windows versions to be sure it works correctly.

**Comment by kliyer** [comment]
Thank you @jhoenicke. @gary-rowe We will be forking hid4java and merging https://github.com/gary-rowe/hid4java/pull/43 so that we can do a release.

**Comment by gary-rowe** [comment]
Hi @kliyer - right now forking is probably the best approach. I'm maxed out with other things and I simply can't spare sufficient time to get the release of hid4java done. I'll be happy to pull in changes that you need into mainline for a later release once it all settles down again.

**Comment by kliyer** [comment]
Thank you @gary-rowe.

**Pull request merged**
